---
- name: Jenkins Container
  hosts: ServerB
  tasks:
    - name: Run Jenkins Container
      ansible.builtin.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        user: 1000
        ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - /vagrant/data/jenkins:/var/jenkins_home
        
    - name: Read Initial Password
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '/vagrant/data/jenkins/secrets/initialAdminPassword') }}"